'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class TechnicalTestEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TechnicalTestEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property products() As DbSet(Of product)
    Public Overridable Property TBL_EMPL() As DbSet(Of TBL_EMPL)

    Public Overridable Function DELETE_PRODUCT(kODE_BARANG As String) As Integer
        Dim kODE_BARANGParameter As ObjectParameter = If(kODE_BARANG IsNot Nothing, New ObjectParameter("KODE_BARANG", kODE_BARANG), New ObjectParameter("KODE_BARANG", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("DELETE_PRODUCT", kODE_BARANGParameter)
    End Function

    Public Overridable Function INSERT_PRODUCT(kODE_BARANG As String, nAMA_BARANG As String, jUMLAH_BARANG As Nullable(Of Integer)) As Integer
        Dim kODE_BARANGParameter As ObjectParameter = If(kODE_BARANG IsNot Nothing, New ObjectParameter("KODE_BARANG", kODE_BARANG), New ObjectParameter("KODE_BARANG", GetType(String)))

        Dim nAMA_BARANGParameter As ObjectParameter = If(nAMA_BARANG IsNot Nothing, New ObjectParameter("NAMA_BARANG", nAMA_BARANG), New ObjectParameter("NAMA_BARANG", GetType(String)))

        Dim jUMLAH_BARANGParameter As ObjectParameter = If(jUMLAH_BARANG.HasValue, New ObjectParameter("JUMLAH_BARANG", jUMLAH_BARANG), New ObjectParameter("JUMLAH_BARANG", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("INSERT_PRODUCT", kODE_BARANGParameter, nAMA_BARANGParameter, jUMLAH_BARANGParameter)
    End Function

    Public Overridable Function SEARCH_PRODUCT(kODE_BARANG As String) As ObjectResult(Of SEARCH_PRODUCT_Result)
        Dim kODE_BARANGParameter As ObjectParameter = If(kODE_BARANG IsNot Nothing, New ObjectParameter("KODE_BARANG", kODE_BARANG), New ObjectParameter("KODE_BARANG", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SEARCH_PRODUCT_Result)("SEARCH_PRODUCT", kODE_BARANGParameter)
    End Function

    Public Overridable Function UPDATE_PRODUCT(kODE_BARANG As String, jUMLAH_BARANG As Nullable(Of Integer)) As Integer
        Dim kODE_BARANGParameter As ObjectParameter = If(kODE_BARANG IsNot Nothing, New ObjectParameter("KODE_BARANG", kODE_BARANG), New ObjectParameter("KODE_BARANG", GetType(String)))

        Dim jUMLAH_BARANGParameter As ObjectParameter = If(jUMLAH_BARANG.HasValue, New ObjectParameter("JUMLAH_BARANG", jUMLAH_BARANG), New ObjectParameter("JUMLAH_BARANG", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UPDATE_PRODUCT", kODE_BARANGParameter, jUMLAH_BARANGParameter)
    End Function

End Class
