'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class product
    Public Property id As Integer
    Public Property nama_barang As String
    Public Property kode_barang As String
    Public Property jumlah_barang As Integer
    Public Property tanggal As Date

End Class
