'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TBL_EMPL
    Public Property EMPLOYEE_ID As Integer
    Public Property EMPLOYEE_NAME As String
    Public Property AGE As Nullable(Of Integer)

End Class
