--B
SELECT * FROM TBL_EMPL WHERE AGE < 45

--C
SELECT A.*, C.DEPARTMENT_NAME FROM TBL_EMPL A 
INNER JOIN TBL_EMPL_DEPT B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
INNER JOIN TBL_DEPT C ON B.DEPARTEMENT_ID = C.DEPARTMENT_ID
WHERE C.DEPARTMENT_NAME = 'Animation'

--D
SELECT A.*, C.MINIMUM_SALARY FROM TBL_EMPL A 
INNER JOIN TBL_EMPL_DEPT B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
INNER JOIN TBL_DEPT C ON B.DEPARTEMENT_ID = C.DEPARTMENT_ID
WHERE C.MINIMUM_SALARY < 4000000