USE [TechnicalTest]
GO

/****** Object:  Table [dbo].[TBL_EMPL]    Script Date: 11/23/2023 10:30:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_EMPL](
	[EMPLOYEE_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_NAME] [nvarchar](max) NULL,
	[AGE] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


CREATE TABLE [dbo].[TBL_EMPL_DEPT](
	[EMPLOYEE_ID] [int] NULL,
	[DEPARTEMENT_ID] [int] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TBL_EMPL_DEPT](
	[EMPLOYEE_ID] [int] NULL,
	[DEPARTEMENT_ID] [int] NULL
) ON [PRIMARY]
GO